version: 2
updates:
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "monthly"
      ignore: # Only suggest major updates for built-in actions
          - dependency-name: "github/*"
            update-types: ["version-update:semver-patch", "version-update:semver-minor"]
          - dependency-name: "actions/*"
            update-types: ["version-update:semver-patch", "version-update:semver-minor"]
    # js dependencies
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "monthly"
